name:                bekkfp-functor-monad-workshop
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/bekkfp-functor-monad-workshop#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - doctest

executables:
  bekkfp-functor-monad-workshop:
    source-dirs:      src
    main:             Main.hs
    when:
    - condition: false
      other-modules: Paths_bekkfp_functor_monad_workshop

tests:
  doctests:
    main: Doctest.hs
    source-dirs: test
    
